/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type V1YoutubeReleaseGet200Response,
    V1YoutubeReleaseGet200ResponseFromJSON,
    V1YoutubeReleaseGet200ResponseToJSON,
} from '../models/V1YoutubeReleaseGet200Response';
import {
    type V1YoutubeReleasesGet200Response,
    V1YoutubeReleasesGet200ResponseFromJSON,
    V1YoutubeReleasesGet200ResponseToJSON,
} from '../models/V1YoutubeReleasesGet200Response';
import {
    type V1YoutubeSongsGet200Response,
    V1YoutubeSongsGet200ResponseFromJSON,
    V1YoutubeSongsGet200ResponseToJSON,
} from '../models/V1YoutubeSongsGet200Response';

export interface V1YoutubeReleaseGetRequest {
    releaseid: string;
}

export interface V1YoutubeReleasesGetRequest {
    channelid: string;
}

export interface V1YoutubeSongsGetRequest {
    channelid: string;
}

/**
 * 
 */
export class YouTubeApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1YoutubeReleaseGet without sending the request
     */
    async v1YoutubeReleaseGetRequestOpts(requestParameters: V1YoutubeReleaseGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['releaseid'] == null) {
            throw new runtime.RequiredError(
                'releaseid',
                'Required parameter "releaseid" was null or undefined when calling v1YoutubeReleaseGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['releaseid'] != null) {
            queryParameters['releaseid'] = requestParameters['releaseid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/youtube/release`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeReleaseGetRaw(requestParameters: V1YoutubeReleaseGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1YoutubeReleaseGet200Response>> {
        const requestOptions = await this.v1YoutubeReleaseGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1YoutubeReleaseGet200ResponseFromJSON(jsonValue));
    }

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeReleaseGet(requestParameters: V1YoutubeReleaseGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1YoutubeReleaseGet200Response> {
        const response = await this.v1YoutubeReleaseGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1YoutubeReleasesGet without sending the request
     */
    async v1YoutubeReleasesGetRequestOpts(requestParameters: V1YoutubeReleasesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelid'] == null) {
            throw new runtime.RequiredError(
                'channelid',
                'Required parameter "channelid" was null or undefined when calling v1YoutubeReleasesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['channelid'] != null) {
            queryParameters['channelid'] = requestParameters['channelid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/youtube/releases`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeReleasesGetRaw(requestParameters: V1YoutubeReleasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1YoutubeReleasesGet200Response>> {
        const requestOptions = await this.v1YoutubeReleasesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1YoutubeReleasesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeReleasesGet(requestParameters: V1YoutubeReleasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1YoutubeReleasesGet200Response> {
        const response = await this.v1YoutubeReleasesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1YoutubeSongsGet without sending the request
     */
    async v1YoutubeSongsGetRequestOpts(requestParameters: V1YoutubeSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelid'] == null) {
            throw new runtime.RequiredError(
                'channelid',
                'Required parameter "channelid" was null or undefined when calling v1YoutubeSongsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['channelid'] != null) {
            queryParameters['channelid'] = requestParameters['channelid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/youtube/songs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeSongsGetRaw(requestParameters: V1YoutubeSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1YoutubeSongsGet200Response>> {
        const requestOptions = await this.v1YoutubeSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1YoutubeSongsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeSongsGet(requestParameters: V1YoutubeSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1YoutubeSongsGet200Response> {
        const response = await this.v1YoutubeSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
