/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XUser } from './XUser';
import {
    XUserFromJSON,
    XUserFromJSONTyped,
    XUserToJSON,
    XUserToJSONTyped,
} from './XUser';
import type { XPost } from './XPost';
import {
    XPostFromJSON,
    XPostFromJSONTyped,
    XPostToJSON,
    XPostToJSONTyped,
} from './XPost';
import type { XRelatePost } from './XRelatePost';
import {
    XRelatePostFromJSON,
    XRelatePostFromJSONTyped,
    XRelatePostToJSON,
    XRelatePostToJSONTyped,
} from './XRelatePost';

/**
 * 
 * @export
 * @interface V1XPostsGet200Response
 */
export interface V1XPostsGet200Response {
    /**
     * 
     * @type {XUser}
     * @memberof V1XPostsGet200Response
     */
    user?: XUser;
    /**
     * List of posts.
     * @type {Array<XPost>}
     * @memberof V1XPostsGet200Response
     */
    posts?: Array<XPost>;
    /**
     * 
     * @type {Array<Array<XRelatePost>>}
     * @memberof V1XPostsGet200Response
     */
    relatedPosts?: Array<Array<XRelatePost>>;
}

/**
 * Check if a given object implements the V1XPostsGet200Response interface.
 */
export function instanceOfV1XPostsGet200Response(value: object): value is V1XPostsGet200Response {
    return true;
}

export function V1XPostsGet200ResponseFromJSON(json: any): V1XPostsGet200Response {
    return V1XPostsGet200ResponseFromJSONTyped(json, false);
}

export function V1XPostsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : XUserFromJSON(json['user']),
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(XPostFromJSON)),
        'relatedPosts': json['relatedPosts'] == null ? undefined : json['relatedPosts'],
    };
}

export function V1XPostsGet200ResponseToJSON(json: any): V1XPostsGet200Response {
    return V1XPostsGet200ResponseToJSONTyped(json, false);
}

export function V1XPostsGet200ResponseToJSONTyped(value?: V1XPostsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': XUserToJSON(value['user']),
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(XPostToJSON)),
        'relatedPosts': value['relatedPosts'],
    };
}

