/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1YoutubeReleasesGet200ResponseReleasesInner
 */
export interface V1YoutubeReleasesGet200ResponseReleasesInner {
    /**
     * 
     * @type {string}
     * @memberof V1YoutubeReleasesGet200ResponseReleasesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1YoutubeReleasesGet200ResponseReleasesInner
     */
    releaseId?: string;
    /**
     * 
     * @type {string}
     * @memberof V1YoutubeReleasesGet200ResponseReleasesInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof V1YoutubeReleasesGet200ResponseReleasesInner
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof V1YoutubeReleasesGet200ResponseReleasesInner
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof V1YoutubeReleasesGet200ResponseReleasesInner
     */
    thumbnailUrl?: string;
}

/**
 * Check if a given object implements the V1YoutubeReleasesGet200ResponseReleasesInner interface.
 */
export function instanceOfV1YoutubeReleasesGet200ResponseReleasesInner(value: object): value is V1YoutubeReleasesGet200ResponseReleasesInner {
    return true;
}

export function V1YoutubeReleasesGet200ResponseReleasesInnerFromJSON(json: any): V1YoutubeReleasesGet200ResponseReleasesInner {
    return V1YoutubeReleasesGet200ResponseReleasesInnerFromJSONTyped(json, false);
}

export function V1YoutubeReleasesGet200ResponseReleasesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1YoutubeReleasesGet200ResponseReleasesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'releaseId': json['releaseId'] == null ? undefined : json['releaseId'],
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'year': json['year'] == null ? undefined : json['year'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
    };
}

export function V1YoutubeReleasesGet200ResponseReleasesInnerToJSON(json: any): V1YoutubeReleasesGet200ResponseReleasesInner {
    return V1YoutubeReleasesGet200ResponseReleasesInnerToJSONTyped(json, false);
}

export function V1YoutubeReleasesGet200ResponseReleasesInnerToJSONTyped(value?: V1YoutubeReleasesGet200ResponseReleasesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'releaseId': value['releaseId'],
        'type': value['type'],
        'title': value['title'],
        'year': value['year'],
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

