/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XPostMediasInnerMediaAspectRatio } from './XPostMediasInnerMediaAspectRatio';
import {
    XPostMediasInnerMediaAspectRatioFromJSON,
    XPostMediasInnerMediaAspectRatioFromJSONTyped,
    XPostMediasInnerMediaAspectRatioToJSON,
    XPostMediasInnerMediaAspectRatioToJSONTyped,
} from './XPostMediasInnerMediaAspectRatio';

/**
 * 
 * @export
 * @interface XPostMediasInnerMedia
 */
export interface XPostMediasInnerMedia {
    /**
     * 
     * @type {string}
     * @memberof XPostMediasInnerMedia
     */
    url?: string;
    /**
     * 
     * @type {XPostMediasInnerMediaAspectRatio}
     * @memberof XPostMediasInnerMedia
     */
    aspectRatio?: XPostMediasInnerMediaAspectRatio;
}

/**
 * Check if a given object implements the XPostMediasInnerMedia interface.
 */
export function instanceOfXPostMediasInnerMedia(value: object): value is XPostMediasInnerMedia {
    return true;
}

export function XPostMediasInnerMediaFromJSON(json: any): XPostMediasInnerMedia {
    return XPostMediasInnerMediaFromJSONTyped(json, false);
}

export function XPostMediasInnerMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): XPostMediasInnerMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'aspectRatio': json['aspectRatio'] == null ? undefined : XPostMediasInnerMediaAspectRatioFromJSON(json['aspectRatio']),
    };
}

export function XPostMediasInnerMediaToJSON(json: any): XPostMediasInnerMedia {
    return XPostMediasInnerMediaToJSONTyped(json, false);
}

export function XPostMediasInnerMediaToJSONTyped(value?: XPostMediasInnerMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'aspectRatio': XPostMediasInnerMediaAspectRatioToJSON(value['aspectRatio']),
    };
}

