/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XPostMediasInnerImage } from './XPostMediasInnerImage';
import {
    XPostMediasInnerImageFromJSON,
    XPostMediasInnerImageFromJSONTyped,
    XPostMediasInnerImageToJSON,
    XPostMediasInnerImageToJSONTyped,
} from './XPostMediasInnerImage';
import type { XPostMediasInnerMedia } from './XPostMediasInnerMedia';
import {
    XPostMediasInnerMediaFromJSON,
    XPostMediasInnerMediaFromJSONTyped,
    XPostMediasInnerMediaToJSON,
    XPostMediasInnerMediaToJSONTyped,
} from './XPostMediasInnerMedia';

/**
 * 
 * @export
 * @interface XPostMediasInner
 */
export interface XPostMediasInner {
    /**
     * 
     * @type {string}
     * @memberof XPostMediasInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof XPostMediasInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof XPostMediasInner
     */
    sourcePostId?: string;
    /**
     * 
     * @type {string}
     * @memberof XPostMediasInner
     */
    sourceUserId?: string;
    /**
     * 
     * @type {XPostMediasInnerMedia}
     * @memberof XPostMediasInner
     */
    media?: XPostMediasInnerMedia;
    /**
     * 
     * @type {XPostMediasInnerImage}
     * @memberof XPostMediasInner
     */
    image?: XPostMediasInnerImage;
}

/**
 * Check if a given object implements the XPostMediasInner interface.
 */
export function instanceOfXPostMediasInner(value: object): value is XPostMediasInner {
    return true;
}

export function XPostMediasInnerFromJSON(json: any): XPostMediasInner {
    return XPostMediasInnerFromJSONTyped(json, false);
}

export function XPostMediasInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): XPostMediasInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'sourcePostId': json['sourcePostId'] == null ? undefined : json['sourcePostId'],
        'sourceUserId': json['sourceUserId'] == null ? undefined : json['sourceUserId'],
        'media': json['media'] == null ? undefined : XPostMediasInnerMediaFromJSON(json['media']),
        'image': json['image'] == null ? undefined : XPostMediasInnerImageFromJSON(json['image']),
    };
}

export function XPostMediasInnerToJSON(json: any): XPostMediasInner {
    return XPostMediasInnerToJSONTyped(json, false);
}

export function XPostMediasInnerToJSONTyped(value?: XPostMediasInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'sourcePostId': value['sourcePostId'],
        'sourceUserId': value['sourceUserId'],
        'media': XPostMediasInnerMediaToJSON(value['media']),
        'image': XPostMediasInnerImageToJSON(value['image']),
    };
}

