/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XPostMediasInner } from './XPostMediasInner';
import {
    XPostMediasInnerFromJSON,
    XPostMediasInnerFromJSONTyped,
    XPostMediasInnerToJSON,
    XPostMediasInnerToJSONTyped,
} from './XPostMediasInner';

/**
 * 
 * @export
 * @interface XRelatePost
 */
export interface XRelatePost {
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    text?: string;
    /**
     * 
     * @type {Date}
     * @memberof XRelatePost
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    replyId?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    repostId?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    quoteRepostId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    urls?: Array<string>;
    /**
     * 
     * @type {Array<XPostMediasInner>}
     * @memberof XRelatePost
     */
    medias?: Array<XPostMediasInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    replyByIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    repostedByIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    quoteRepostByIds?: Array<string>;
}

/**
 * Check if a given object implements the XRelatePost interface.
 */
export function instanceOfXRelatePost(value: object): value is XRelatePost {
    return true;
}

export function XRelatePostFromJSON(json: any): XRelatePost {
    return XRelatePostFromJSONTyped(json, false);
}

export function XRelatePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): XRelatePost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'replyId': json['replyId'] == null ? undefined : json['replyId'],
        'repostId': json['repostId'] == null ? undefined : json['repostId'],
        'quoteRepostId': json['quoteRepostId'] == null ? undefined : json['quoteRepostId'],
        'urls': json['urls'] == null ? undefined : json['urls'],
        'medias': json['medias'] == null ? undefined : ((json['medias'] as Array<any>).map(XPostMediasInnerFromJSON)),
        'replyByIds': json['replyByIds'] == null ? undefined : json['replyByIds'],
        'repostedByIds': json['repostedByIds'] == null ? undefined : json['repostedByIds'],
        'quoteRepostByIds': json['quoteRepostByIds'] == null ? undefined : json['quoteRepostByIds'],
    };
}

export function XRelatePostToJSON(json: any): XRelatePost {
    return XRelatePostToJSONTyped(json, false);
}

export function XRelatePostToJSONTyped(value?: XRelatePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'userId': value['userId'],
        'replyId': value['replyId'],
        'repostId': value['repostId'],
        'quoteRepostId': value['quoteRepostId'],
        'urls': value['urls'],
        'medias': value['medias'] == null ? undefined : ((value['medias'] as Array<any>).map(XPostMediasInnerToJSON)),
        'replyByIds': value['replyByIds'],
        'repostedByIds': value['repostedByIds'],
        'quoteRepostByIds': value['quoteRepostByIds'],
    };
}

