/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User information.
 * @export
 * @interface XUser
 */
export interface XUser {
    /**
     * 
     * @type {string}
     * @memberof XUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof XUser
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof XUser
     */
    profileImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof XUser
     */
    userName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof XUser
     */
    userNameHistory?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof XUser
     */
    postLastUpdated?: Date;
    /**
     * 
     * @type {Date}
     * @memberof XUser
     */
    userLastUpdated?: Date;
}

/**
 * Check if a given object implements the XUser interface.
 */
export function instanceOfXUser(value: object): value is XUser {
    return true;
}

export function XUserFromJSON(json: any): XUser {
    return XUserFromJSONTyped(json, false);
}

export function XUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): XUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'profileImageUrl': json['profileImageUrl'] == null ? undefined : json['profileImageUrl'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'userNameHistory': json['userNameHistory'] == null ? undefined : json['userNameHistory'],
        'postLastUpdated': json['postLastUpdated'] == null ? undefined : (new Date(json['postLastUpdated'])),
        'userLastUpdated': json['userLastUpdated'] == null ? undefined : (new Date(json['userLastUpdated'])),
    };
}

export function XUserToJSON(json: any): XUser {
    return XUserToJSONTyped(json, false);
}

export function XUserToJSONTyped(value?: XUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'profileImageUrl': value['profileImageUrl'],
        'userName': value['userName'],
        'userNameHistory': value['userNameHistory'],
        'postLastUpdated': value['postLastUpdated'] == null ? value['postLastUpdated'] : value['postLastUpdated'].toISOString(),
        'userLastUpdated': value['userLastUpdated'] == null ? value['userLastUpdated'] : value['userLastUpdated'].toISOString(),
    };
}

