/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YoutubeRelease
 */
export interface YoutubeRelease {
    /**
     * 
     * @type {string}
     * @memberof YoutubeRelease
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof YoutubeRelease
     */
    listIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof YoutubeRelease
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeRelease
     */
    videoId?: string;
    /**
     * 
     * @type {number}
     * @memberof YoutubeRelease
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof YoutubeRelease
     */
    releaseVideoId?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeRelease
     */
    playlistId?: string;
}

/**
 * Check if a given object implements the YoutubeRelease interface.
 */
export function instanceOfYoutubeRelease(value: object): value is YoutubeRelease {
    return true;
}

export function YoutubeReleaseFromJSON(json: any): YoutubeRelease {
    return YoutubeReleaseFromJSONTyped(json, false);
}

export function YoutubeReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): YoutubeRelease {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'listIndex': json['listIndex'] == null ? undefined : json['listIndex'],
        'title': json['title'] == null ? undefined : json['title'],
        'videoId': json['videoId'] == null ? undefined : json['videoId'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'releaseVideoId': json['releaseVideoId'] == null ? undefined : json['releaseVideoId'],
        'playlistId': json['playlistId'] == null ? undefined : json['playlistId'],
    };
}

export function YoutubeReleaseToJSON(json: any): YoutubeRelease {
    return YoutubeReleaseToJSONTyped(json, false);
}

export function YoutubeReleaseToJSONTyped(value?: YoutubeRelease | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'listIndex': value['listIndex'],
        'title': value['title'],
        'videoId': value['videoId'],
        'duration': value['duration'],
        'releaseVideoId': value['releaseVideoId'],
        'playlistId': value['playlistId'],
    };
}

