/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YoutubeReleases
 */
export interface YoutubeReleases {
    /**
     * 
     * @type {string}
     * @memberof YoutubeReleases
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeReleases
     */
    releaseId?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeReleases
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeReleases
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof YoutubeReleases
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof YoutubeReleases
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof YoutubeReleases
     */
    duration?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof YoutubeReleases
     */
    artistChannelIds?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof YoutubeReleases
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof YoutubeReleases
     */
    lastUpdated?: Date;
}

/**
 * Check if a given object implements the YoutubeReleases interface.
 */
export function instanceOfYoutubeReleases(value: object): value is YoutubeReleases {
    return true;
}

export function YoutubeReleasesFromJSON(json: any): YoutubeReleases {
    return YoutubeReleasesFromJSONTyped(json, false);
}

export function YoutubeReleasesFromJSONTyped(json: any, ignoreDiscriminator: boolean): YoutubeReleases {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'releaseId': json['releaseId'] == null ? undefined : json['releaseId'],
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'year': json['year'] == null ? undefined : json['year'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'artistChannelIds': json['artistChannelIds'] == null ? undefined : json['artistChannelIds'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastUpdated': json['lastUpdated'] == null ? undefined : (new Date(json['lastUpdated'])),
    };
}

export function YoutubeReleasesToJSON(json: any): YoutubeReleases {
    return YoutubeReleasesToJSONTyped(json, false);
}

export function YoutubeReleasesToJSONTyped(value?: YoutubeReleases | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'releaseId': value['releaseId'],
        'type': value['type'],
        'title': value['title'],
        'year': value['year'],
        'thumbnailUrl': value['thumbnailUrl'],
        'duration': value['duration'],
        'artistChannelIds': value['artistChannelIds'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'lastUpdated': value['lastUpdated'] == null ? value['lastUpdated'] : value['lastUpdated'].toISOString(),
    };
}

